### PR TITLE
feat: get path separator

### PR DESCRIPTION
**Pull request by tomzohar**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: [CONTRIBUTING.md](CONTRIBUTING.md#commit-message-format)
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?
add api GET path separator

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #9 

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by Danieliverant — COMMENTED** [review]
Can you add sone info about this PR? I can't get what this endpoint for

**Comment by Danieliverant** [comment]
> > Can you add sone info about this PR? I can't get what this endpoint for
> 
> sure, we are allowing the user to navigate the filesystem. but for every OS the path separator might be different for example: MacOS: '/' Windows: '\' so we need to know which separator to use in order to send valid path to the server this endpoint will return the separator and the client can build the path according to the user OS

But why we can't always display "/" and for querying the server will use it as the inner logic?

**Comment by tomzohar** [comment]
> > > Can you add sone info about this PR? I can't get what this endpoint for
> > 
> > 
> > sure, we are allowing the user to navigate the filesystem. but for every OS the path separator might be different for example: MacOS: '/' Windows: '' so we need to know which separator to use in order to send valid path to the server this endpoint will return the separator and the client can build the path according to the user OS
> 
> But why we can't always display "/" and for querying the server will use it as the inner logic?

we can do that, but let's say we want to have the ability to copy the path to the clipboard, wouldn't it be easier if just display the actual separator in the UI ?

**Comment by Danieliverant** [comment]
> > > > Can you add sone info about this PR? I can't get what this endpoint for
> > > 
> > > 
> > > sure, we are allowing the user to navigate the filesystem. but for every OS the path separator might be different for example: MacOS: '/' Windows: '' so we need to know which separator to use in order to send valid path to the server this endpoint will return the separator and the client can build the path according to the user OS
> > 
> > 
> > But why we can't always display "/" and for querying the server will use it as the inner logic?
> 
> we can do that, but let's say we want to have the ability to copy the path to the clipboard, wouldn't it be easier if just display the actual separator in the UI ? this would also mean sanitizing the string in the BE, so more work and more places to have errors

good point

**Pull request merged**
